data:extend({
	{
		type = "string-setting",
		name = "deep-space-sensing-locations",
		setting_type = "startup",
		default_value = "aquilo, solar-system-edge",
		allow_blank = true,
		order = "a",
	},
	{
		type = "double-setting",
		name = "deep-space-sensing-default-hardness",
		setting_type = "startup",
		default_value = 6.0,
		minimum_value = 0.0,
		maximum_value = 100.0,
		order = "b",
	},
	{
		type = "double-setting",
		name = "deep-space-sensing-global-hardness-multiplier",
		setting_type = "startup",
		default_value = 1.0,
		minimum_value = 0.1,
		maximum_value = 10.0,
		order = "b-b",
	},
	{
		type = "double-setting",
		name = "deep-space-sensing-default-minimum-strength",
		setting_type = "startup",
		default_value = 2.0,
		minimum_value = 0.0,
		maximum_value = 100.0,
		order = "c",
	},
	{
		type = "double-setting",
		name = "deep-space-sensing-default-base-contribution-scale",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.001,
		maximum_value = 1.0,
		order = "d",
	},
	{
		type = "double-setting",
		name = "deep-space-sensing-default-decay-scale",
		setting_type = "startup",
		default_value = 20,
		minimum_value = 1.0,
		maximum_value = 1000,
		order = "e",
	},
	{
		type = "int-setting",
		name = "deep-space-sensing-default-orbital-capacity",
		setting_type = "startup",
		default_value = 500,
		minimum_value = 10,
		maximum_value = 10000,
		order = "f",
	},
	{
		type = "double-setting",
		name = "deep-space-sensing-default-attrition-rate",
		setting_type = "startup",
		default_value = 0.001,
		minimum_value = 0.0,
		maximum_value = 0.1,
		order = "g",
	},
})
